### PR TITLE
ISSUE-78 add grpc support for brpc

### PR DESCRIPTION
**Pull request by Kewei-Wang-Kevin**
## Motivation
Add GRPC support for BRPC in java project

## Status 
Now, this PR has implemented the following features:
1. GrpcServer boot and deploy service(classical GRPC service)
2. Bind BRPC service to GRPC server and the service which was written by BRPC can be invoked by 
the GRPC client

### CODE REVIEW

**Comment by wenweihu86** [comment]
@Kewei-Wang-Kevin Thanks for your pull request.
I have some suggestions, I don't know if it works.
Could you implement Protocol interface like http protocols which is the package protocol/http, and reuse RpcServer/RpcClient/LoadBalance/ConnectionPool/NamingService etc?

**Comment by Kewei-Wang-Kevin** [comment]
> @Kewei-Wang-Kevin Thanks for your pull request.
> I have some suggestions, I don't know if it works.
> Could you implement Protocol interface like http protocols which is the package protocol/http, and reuse RpcServer/RpcClient/LoadBalance/ConnectionPool/NamingService etc?

In the beginning of my working, I also hope that I can reuse existed code as much as possible, but after I investigative, I found that it is really hard to reuse the protocol part, which is the entry for all RPC process starts, here is the reason:

1. the interacting mechanism between GRPC and other RPC protocols in BRPC has a significant difference. the basic assumption of other RPC protocol is ***one request with one response***,
here is the sequence:
```
Client->Server:Request
Server-->>Client:Response
```
under this order, we can use a standard process that you have implemented in BRPC, but for GRPC, the sequence is:
```
Client->Server:Request(Http2/MAGIC,SETTINGS)
Server-->>Client:Response(Http2/ SETTINGS)
Client->Server:Request(Http2/Header Frame)
Server-->Client:Response(Http2/OK)
Client->ServerRequest(Http2/Data Frame)
Server-->Client:Response(Http2/Data Frame)//GRPC will also got response here
```
you should notice the whole RPC has been split into several parts, which can't match the current way in BRPC.
And here is the network package that I captured by Wireshark
image
it means that if you want to support GRPC in netty, you need to support HTTP2 first, and then, based on the support of Http2, you can start supporting GRPC. which is reinventing the wheel.

So under such a circumstance, it is hard to reuse the protocol part. and I choose to use grpc's internal API to make it work with BRPC. 

2. The implementation of your own business logic based on BRPC and GRPC is also different. that's the reason why I created a new kind of server called ***GrpcServer***, for BRPC, you prefer to define a Service interface, and then implement it, and you will use a kind of ***Proxy*** technology make a delegate such `JDK Proxy` or `cglib` of your service.  but in GRPC, the philosophy is use generated code instead of any ***reflection*** and ***bytecode wave*** things. so when you are using GRPC, you need to extend from the base class and rewrite methods, and it means that the perform of `registeService` become different as well

Although we have some difficulties in reuse protocol part and server part in BRPC, it is still possible to reuse other fundamental code in BRPC project,  for example, in the server side, I have reused the ***NamingService*** for service registration, and I think in the client side, I can also reuse the LoadBalance and Service discovery functions.

How do you think about that?

**Comment by wenweihu86** [comment]
@Kewei-Wang-Kevin current implementation can talk with grpc effectively, but I think it is better to implement http2 and grpc protocol, so that it is consistent with other protocols in brpc.
grpc Stub client can be implemented by java proxy, please see brpc standard protocol.

**Comment by Kewei-Wang-Kevin** [comment]
Since there are too many commits in this pr,  I will close this pr and create a new pr for grpc implementation

**Pull request closed without merging**
